import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service | VoiceDrop',
  description: 'Terms of Service for VoiceDrop by Anteratic Solutions',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col font-sans">
      {/* Minimal header */}
      <header className="w-full px-6 py-5 flex items-center justify-between border-b border-outline-variant/20">
        <Link href="/" className="flex items-center gap-2 hover:opacity-75 transition-opacity">
          <span className="material-symbols-outlined text-primary" style={{ fontSize: '22px' }} aria-hidden="true">settings_voice</span>
          <span className="text-lg font-extrabold tracking-tighter text-primary">VoiceDrop</span>
        </Link>
        <Link href="/" className="text-[0.65rem] uppercase tracking-widest font-bold text-on-surface-variant hover:text-on-surface transition-colors">
          ← Back
        </Link>
      </header>

      <main className="flex-grow max-w-2xl mx-auto w-full px-6 py-12 space-y-8">
        <div className="space-y-2">
          <p className="text-[0.65rem] uppercase tracking-[0.12em] font-bold text-primary">Legal</p>
          <h1 className="text-3xl font-extrabold text-on-surface tracking-tight">Terms of Service</h1>
          <p className="text-on-surface-variant text-sm">Anteratic Solutions · Effective 29 March 2026</p>
        </div>

        <div className="prose-sm space-y-6 text-on-surface-variant leading-relaxed">
          <section className="space-y-2">
            <h2 className="text-on-surface font-bold text-base">1. Service</h2>
            <p>
              VoiceDrop is an AI-powered service that converts article URLs into two-host podcast audio. It is operated by <strong className="text-on-surface">Anteratic Solutions</strong>. By using VoiceDrop, you agree to these terms.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-on-surface font-bold text-base">2. Eligibility</h2>
            <p>You must be at least 13 years old to use VoiceDrop. By creating an account you confirm you meet this requirement.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-on-surface font-bold text-base">3. Plan limits</h2>
            <p>Each plan includes a monthly podcast generation allowance that resets on the 1st of each calendar month:</p>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li><strong className="text-on-surface">Free</strong> — 3 podcasts per month, up to 1 minute each</li>
              <li><strong className="text-on-surface">Starter</strong> — 20 podcasts per month, up to 2 minutes each</li>
              <li><strong className="text-on-surface">Pro</strong> — 100 podcasts per month, up to 3 minutes each</li>
              <li><strong className="text-on-surface">Enterprise</strong> — unlimited podcasts, up to 3 minutes each</li>
            </ul>
            <p>Unused allowances do not roll over. Limits are enforced server-side and cannot be circumvented.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-on-surface font-bold text-base">4. Payments and refunds</h2>
            <p>Paid plans are billed monthly via Stripe. Subscription fees are non-refundable once a billing cycle has commenced. You may cancel at any time — your plan remains active until the end of the current billing period. No refunds are issued for partially used months or consumed podcast generations.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-on-surface font-bold text-base">5. Acceptable use</h2>
            <p>You agree not to use VoiceDrop to:</p>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li>Generate content that is unlawful, hateful, defamatory, or abusive</li>
              <li>Submit URLs to content that you do not have a right to process</li>
              <li>Attempt to bypass plan limits or circumvent authentication</li>
              <li>Resell or redistribute generated audio as your own AI product without a white-label agreement</li>
              <li>Use the service in any way that could damage, disable, or impair our infrastructure</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-on-surface font-bold text-base">6. Intellectual property</h2>
            <p>Audio generated by VoiceDrop using content you supply is owned by you, subject to any copyright that exists in the underlying article. Anteratic Solutions makes no claim over your generated content. The VoiceDrop platform, brand, and underlying technology remain the property of Anteratic Solutions.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-on-surface font-bold text-base">7. AI-generated content disclaimer</h2>
            <p>VoiceDrop uses large language models to generate podcast dialogue. Generated content may be inaccurate, incomplete, or outdated. It is your responsibility to verify any information before relying on it. Anteratic Solutions is not liable for errors in AI-generated content.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-on-surface font-bold text-base">8. Availability</h2>
            <p>We aim for high availability but do not guarantee uninterrupted service. We may modify, suspend, or discontinue features at any time. We will endeavour to provide reasonable notice for significant changes.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-on-surface font-bold text-base">9. Limitation of liability</h2>
            <p>To the maximum extent permitted by law, Anteratic Solutions shall not be liable for any indirect, incidental, consequential, or punitive damages arising from your use of VoiceDrop. Our aggregate liability shall not exceed the amount you paid us in the three months preceding a claim.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-on-surface font-bold text-base">10. Governing law</h2>
            <p>These terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in India.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-on-surface font-bold text-base">11. Contact</h2>
            <p>For questions about these terms, email <a href="mailto:legal@anteratic.com" className="text-primary hover:underline">legal@anteratic.com</a>.</p>
          </section>
        </div>
      </main>

      <footer className="w-full py-4 border-t border-outline-variant/20 text-center">
        <p className="text-[0.6rem] uppercase tracking-widest text-on-surface-variant/40">
          © 2026 Anteratic Solutions · <Link href="/privacy" className="hover:text-primary transition-colors">Privacy</Link>
        </p>
      </footer>
    </div>
  );
}
